const data = {
    "read": {
        "en": {
            "title": "The Need to Read",
            "author": "Paul Graham",
            "date": "November 2022",
            "name": "read",
            "lang": "en",
            "url": "http://www.paulgraham.com/read.html",
            "it": [
                "In the science fiction books I read as a kid,",
                "reading had often been replaced by some more efficient way of acquiring knowledge.",
                "Mysterious \"tapes\" would load it into one's brain like a program being loaded into a computer.",
                "That sort of thing is unlikely to happen anytime soon.",
                "Not just because it would be hard to build a replacement for reading,",
                "but because even if one existed, it would be insufficient.",
                "Reading about x doesn't just teach you about x; it also teaches you how to write. [1]",
                "Would that matter? If we replaced reading, would anyone need to be good at writing?",
                "The reason it would matter is that writing is not just a way to convey ideas, but also a way to have them.",
                "A good writer doesn't just think, and then write down what he thought, as a sort of transcript.",
                "A good writer will almost always discover new things in the process of writing.",
                "And there is, as far as I know, no substitute for this kind of discovery.",
                "Talking about your ideas with other people is a good way to develop them.",
                "But even after doing this, you'll find you still discover new things when you sit down to write.",
                "There is a kind of thinking that can only be done by writing.",
                "There are of course kinds of thinking that can be done without writing.",
                "If you don't need to go too deeply into a problem, you can solve it without writing.",
                "If you're thinking about how two pieces of machinery should fit together, writing about it probably won't help much.",
                "And when a problem can be described formally, you can sometimes solve it in your head.",
                "But if you need to solve a complicated, ill-defined problem, it will almost always help to write about it.",
                "Which in turn means that someone who's not good at writing will almost always be at a disadvantage in solving such problems.",
                "You can't think well without writing well, and you can't write well without reading well.",
                "And I mean that last \"well\" in both senses. You have to be good at reading, and read good things. [2]",
                "People who just want information may find other ways to get it.",
                "But people who want to have ideas can't afford to.",
                "Notes [1] Audiobooks can give you examples of good writing,",
                "but having them read to you doesn't teach you as much about writing as reading them yourself.",
                "[2] By \"good at reading\" I don't mean good at the mechanics of reading.",
                "You don't have to be good at extracting words from the page so much as extracting meaning from the words."
            ]
        },
        "it": {
            "title": "La necessit\u00e0 di leggere",
            "author": "Marco Trombetti",
            "date": "Novembre 2022",
            "name": "read",
            "lang": "it",
            "url": "https://marcotrombetti.com/leggere",
            "en": [
                "Nei libri di fantascienza che leggevo da bambino,",
                "la lettura era stata spesso sostituita da un modo pi\u00f9 efficiente di acquisire conoscenza.",
                "\"bobine\" misteriose caricherebbero conoscenza nel cervello come avviene con un programma per computer.",
                "\u00c8 improbabile che qualcosa di simile accada presto.",
                "Non solo perch\u00e9 sarebbe difficile costruire un sostituto per la lettura,",
                "ma anche perch\u00e9 se ne esistesse uno, sarebbe insufficiente.",
                "Leggere di X non solo ti insegna di X; ti insegna anche a scrivere. [1]",
                "E\u2019 importante? Se sostituissimo la lettura, perch\u00e9 si dovrebbe comunque essere bravi a scrivere?",
                "Il motivo per cui sarebbe importante \u00e8 che la scrittura non \u00e8 solo un modo per trasmettere idee, ma anche un modo per averle.",
                "Un buon scrittore non si limita a pensare, e poi, come una sorta di trascrizione, scrivere quello che ha pensato.",
                "Un buono scrittore quasi sempre scoprir\u00e0 delle cose nuove nel processo di scrittura.",
                "E per quanto ne sappia io, non c\u2019\u00e8 nessun sostituto a questo modo di scoprire.",
                "Parlare delle tue idee con altre persone \u00e8 un buon modo per svilupparle.",
                "Ma anche dopo averlo fatto, scoprirai ancora nuove cose quando ti siederai a scrivere.",
                "C\u2019\u00e8 un modo di ragionare che avviene solo scrivendo.",
                "Ci sono naturalmente generi di ragionamento che possono essere fatti senza scrittura.",
                "Se non hai bisogno di approfondire troppo un problema, puoi risolverlo senza scrivere.",
                "Se stai pensando a come due pezzi di un macchinario dovrebbero stare insieme, scriverne probabilmente non aiuter\u00e0 molto.",
                "E quando un problema pu\u00f2 essere descritto formalmente, a volte puoi risolverlo nella tua testa.",
                "Ma se avete bisogno di risolvere un problema complicato, mal definito, quasi sempre vi aiuter\u00e0 scriverne.",
                "Il che a sua volta significa che qualcuno che non \u00e8 bravo a scrivere sar\u00e0 quasi sempre svantaggiato nel risolvere tali problemi.",
                "Non si pu\u00f2 pensare bene senza scrivere bene, e non si pu\u00f2 scrivere bene senza leggere bene.",
                "E intendo l\u2019ultimo \"bene\" in entrambi i sensi. Devi essere bravi a leggere, e leggere cose buone. [2]",
                "Le persone che vogliono solo informazioni, possono trovare altri modi per ottenerle.",
                "Ma le persone che vogliono avere idee non possono permetterselo.",
                "Note [1] Gli audiolibri possono darti esempi di buona scrittura,",
                "ma averli ascoltati non ti insegna tanto a scrivere quanto a leggerli tu stesso.",
                "[2] Con \"bravi a leggere\" non intendo bravi nella meccanica della lettura.",
                "Non c\u2019\u00e8 bisogno di essere bravi a estrarre parole dalla pagina, tanto quanto a estrarre significato dalle parole."
            ]
        }
    },
    "writing44": {
        "de": {
            "title": "Schreiben \u2013 kurz gefasst",
            "author": "Volker Diels-Grabsch, Tobias Florek and Berit Gru\u00dfien",
            "date": "M\u00e4rz 2005",
            "name": "writing44",
            "lang": "de",
            "url": "http://wiki.njh.eu/Schreiben_-_kurz_gefasst",
            "en": [
                "(Als ich eine E-Mail beantwortete,",
                "schrieb ich zuf\u00e4llig einen kleinen Essay \u00fcber das Schreiben.",
                "Normalerweise arbeite ich an einem Essay wochenlang.",
                "F\u00fcr diesen hier brauchte ich nur 67 Minuten \u2013 23 zum Schreiben, und 44 zum \u00dcberarbeiten.)",
                "Ich denke, es ist viel wichtiger, gut zu schreiben, als den meisten Leuten klar ist.",
                "Schreiben vermittelt nicht nur Ideen; es erzeugt sie.",
                "Wenn du im Schreiben schlecht bist und es deshalb nicht magst, wirst du auf viele Ideen verzichten, die dir sonst beim Schreiben gekommen w\u00e4ren.",
                "Zum guten Schreibstil hier eine Kurzfassung:",
                "Schreibe so schnell es geht eine schlechte erste Version.",
                "\u00dcberarbeite sie wieder und wieder.",
                "K\u00fcrze alles Unn\u00f6tige heraus.",
                "Schreibe in umgangssprachlichem Ton.",
                "Entwickle einen Riecher f\u00fcr schlechtes Schreiben, sodass du es in deinen eigenen Texten bemerkst und beheben kannst.",
                "Imitiere Autoren, die du magst.",
                "Wenn du keinen Anfang findest, erz\u00e4hle jemanden, wor\u00fcber du schreiben m\u00f6chtest. Dann schreibe auf, was du ihm erz\u00e4hlt hast.",
                "Rechne damit, dass 80% deiner Ideen erst beim Schreiben kommen, und 50% deiner urspr\u00fcnglichen Ideen Unsinn waren.",
                "Sei selbstsicher genug, auch zu streichen.",
                "Vertraue das Geschriebene Freunden an, die dir verwirrende und holperige Stellen aufzeigen.",
                "Beginne nicht (immer) mit einem auf\u00fchrlichen Konzept.",
                "\u00dcberdenke deine Ideen ein paar Tage, bevor du mit dem Schreiben beginnst.",
                "Trage einen kleinen Notizblock oder Schmierzettel mit dir herum.",
                "Beginne mit dem Schreiben, sobald dir ein Anfangs-Satz einf\u00e4llt.",
                "Wenn dich ein Abgabetermin zwingt, vorher zu beginnen, w\u00e4hle einfach den wichtigsten Satz als Anfang.",
                "Schreibe \u00fcber etwas, das du magst.",
                "Versuche nicht, eindrucksvoll zu klingen.",
                "Z\u00f6gere nicht, nebenher den Titel zu \u00e4ndern.",
                "Benutze Fu\u00dfnoten, um Ausschweifungen aufzufangen.",
                "Benutze Anaphern, die deine S\u00e4tze zusammenhalten.",
                "Lese deine Essays laut vor, um zu sehen, an welchen Stellen du \u00fcber schwierige S\u00e4tze stolperst, und welche Stellen langweilig sind (die Abs\u00e4tze, die du nicht mehr sehen kannst).",
                "Versuche, dem Leser etwas Neues und N\u00fctzliches mitzuteilen.",
                "Arbeite in m\u00f6glichst gro\u00dfen Zeitbl\u00f6cken.",
                "Wenn du dich wieder daran setzt, beginne damit, deinen bisherigen Text nochmals durchzulesen.",
                "Wenn du aufh\u00f6rst, lass dir etwas Einfaches \u00fcbrig, mit dem du sp\u00e4ter wieder anfangen m\u00f6chtest.",
                "Sammle Notizen \u00fcber die Themen zuk\u00fcnftiger Essays am Ende der Datei.",
                "F\u00fchle dich nicht verpflichtet, irgendeine davon in die Tat umzusetzen.",
                "Schreibe f\u00fcr Leute, die den Essay niemals so gr\u00fcndlich lesen werden wie du; genauso wie Popmusik daf\u00fcr geschaffen ist, auch auf schrottigen Autoradios vern\u00fcnftig zu klingen.",
                "Wenn du irgend etwas Falsches schreibst, korrigier es unverz\u00fcglich.",
                "Frage deine Freunde, welchen Satz du sp\u00e4ter am meisten bereuhen wirst.",
                "Setze dich wieder an den Text und entsch\u00e4rfe die bissigen Bemerkungen.",
                "Ver\u00f6ffentliche deinen Kram im Internet, denn eine Leserschaft motiviert dich, mehr zu schreiben, wodurch dir mehr Ideen kommen.",
                "Drucke deine Entw\u00fcrfe aus, statt sie nur am Bildschirm zu betrachten.",
                "Benutze einfache, deutsche Worte.",
                "Erlerne den Unterschied zwischen Verbl\u00fcffungen und Ausschweifungen.",
                "Lerne, ein auftauchendes Ende zu erkennen. Sobald sich eines anbietet, greif zu!"
            ]
        },
        "es": {
            "title": "Escribir, en pocas palabras",
            "author": "Matias Andina",
            "date": "Marzo de 2005",
            "name": "writing44",
            "lang": "es",
            "url": "https://matiasandina.netlify.com/2020/01/escribiendo-en-pocas-palabras/",
            "en": [
                "(En el proceso de responder un email,",
                "escrib\u00ed accidentalmente un peque\u00f1o ensayo sobre c\u00f3mo escribir.",
                "Normalmente dedico semanas a cada ensayo.",
                "Este tard\u00f3 67 minutos \u2013 23 para escribirlo y 44 para reescribirlo.)",
                "Creo que escribir bien es mucho m\u00e1s importante que lo que la gente se imagina.",
                "Escribir no s\u00f3lo comunica ideas, las genera.",
                "Si eres malo escribiendo y no te gusta hacerlo, perder\u00e1s la oportunidad de generar la mayor\u00eda de las ideas que la escritura te hubiera regalado.",
                "En cuanto a c\u00f3mo escribir bien, aqu\u00ed dejo una breve sugerencia:",
                "Escribe una primera versi\u00f3n mala tan r\u00e1pido como puedas;",
                "rescr\u00edbela una y otra vez;",
                "remueve todo aquello que sea innecesario;",
                "escribe en un tono de conversaci\u00f3n;",
                "desarrolla un buen olfato para detectar malos escritos, de modo que as\u00ed puedas arreglar los tuyos;",
                "imita a escritores que te gusten;",
                "Si no puedes empezar, cu\u00e9ntale a alguien sobre lo que planeas escribir, luego escribe lo que les contaste;",
                "ten en cuenta que 80% de las ideas en un ensayo ocurren despu\u00e9s de empezar a escribirlo,",
                "y 50% de las ideas con las que empiezas estar\u00e1n erradas;",
                "mant\u00e9n la confianza para remover texto;",
                "comparte tus textos con amigos de confianza, para que te digan qu\u00e9 partes son confusas o lentas;",
                "no siempre es necesario empezar con un esquema del texto;",
                "reflexiona sobre las ideas por un par de d\u00edas antes de escribirlas;",
                "lleva contigo un anotador o pedazos sueltos de papel;",
                "empieza a escribir cuando pienses en la primera oraci\u00f3n;",
                "si una fecha l\u00edmite te fuerza a empezar antes de tener la primera frase, escoge la frase m\u00e1s importante para comenzar;",
                "escribe sobre cosas que te gusten;",
                "no trates de impresionar con tu vocabulario;",
                "no dudes en cambiar el t\u00f3pico en el medio del texto;",
                "usa notas al pie para conservar digresiones;",
                "usa an\u00e1foras para entretejer las oraciones;",
                "lee tus ensayos en voz alta para ver (a) d\u00f3nde suenan extra\u00f1os y (b) qu\u00e9 pedazos son aburridos (aquellos que odias leer);",
                "intenta decirle al lector algo nuevo y \u00fatil;",
                "trabaja durante per\u00edodos prolongados;",
                "cuando debas comenzar de nuevo, hazlo releyendo lo que tienes hasta ahora;",
                "cuando debas terminar, deja algo que facilite comenzar de nuevo;",
                "acumula notas de t\u00f3picos que planeas escribir al final del archivo;",
                "no te sientas obligado a tratar ninguno de ellos;",
                "escribe para un lector que no va a leer tu ensayo con tanto cuidado como t\u00fa,",
                "del mismo modo que las canciones pop fueron dise\u00f1adas para sonar de manera aceptable en radios baratas;",
                "si dices algo equivocado, corr\u00edgelo inmediatamente;",
                "pregunta a amigos cu\u00e1les son las oraciones de las que te arrepentir\u00e1s;",
                "vuelve al texto y baja el tono de los comentarios duros;",
                "publica tus textos online, porque tener una audiencia te hace escribir m\u00e1s y, por lo tanto, generar m\u00e1s ideas;",
                "imprime borradores en vez de mirarlos en la pantalla;",
                "utiliza palabras simples;",
                "aprende a distinguir sorpresas de digresiones;",
                "aprende a reconocer la oportunidad para finalizar y, cuando uno aparezca, t\u00f3mala."
            ]
        },
        "en": {
            "title": "Writing, Briefly",
            "author": "Paul Graham",
            "date": "March 2005",
            "name": "writing44",
            "lang": "en",
            "url": "http://www.paulgraham.com/writing44.html",
            "de": [
                "(In the process of answering an email,",
                "I accidentally wrote a tiny essay about writing.",
                "I usually spend weeks on an essay.",
                "This one took 67 minutes\u201423 of writing, and 44 of rewriting.)",
                "I think it's far more important to write well than most people realize.",
                "Writing doesn't just communicate ideas; it generates them.",
                "If you're bad at writing and don't like to do it, you'll miss out on most of the ideas writing would have generated.",
                "As for how to write well, here's the short version:",
                "Write a bad version 1 as fast as you can;",
                "rewrite it over and over;",
                "cut out everything unnecessary;",
                "write in a conversational tone;",
                "develop a nose for bad writing, so you can see and fix it in yours;",
                "imitate writers you like;",
                "if you can't get started, tell someone what you plan to write about, then write down what you said;",
                "expect 80% of the ideas in an essay to happen after you start writing it, and 50% of those you start with to be wrong;",
                "be confident enough to cut;",
                "have friends you trust read your stuff and tell you which bits are confusing or drag;",
                "don't (always) make detailed outlines;",
                "mull ideas over for a few days before writing;",
                "carry a small notebook or scrap paper with you;",
                "start writing when you think of the first sentence;",
                "if a deadline forces you to start before that, just say the most important sentence first;",
                "write about stuff you like;",
                "don't try to sound impressive;",
                "don't hesitate to change the topic on the fly;",
                "use footnotes to contain digressions;",
                "use anaphora to knit sentences together;",
                "read your essays out loud to see (a) where you stumble over awkward phrases and (b) which bits are boring (the paragraphs you dread reading);",
                "try to tell the reader something new and useful;",
                "work in fairly big quanta of time;",
                "when you restart, begin by rereading what you have so far;",
                "when you finish, leave yourself something easy to start with;",
                "accumulate notes for topics you plan to cover at the bottom of the file;",
                "don't feel obliged to cover any of them;",
                "write for a reader who won't read the essay as carefully as you do, just as pop songs are designed to sound ok on crappy car radios;",
                "if you say anything mistaken, fix it immediately;",
                "ask friends which sentence you'll regret most;",
                "go back and tone down harsh remarks;",
                "publish stuff online, because an audience makes you write more, and thus generate more ideas;",
                "print out drafts instead of just looking at them on the screen;",
                "use simple, germanic words;",
                "learn to distinguish surprises from digressions;",
                "learn to recognize the approach of an ending, and when one appears, grab it."
            ],
            "es": [
                "(In the process of answering an email,",
                "I accidentally wrote a tiny essay about writing.",
                "I usually spend weeks on an essay.",
                "This one took 67 minutes\u201423 of writing, and 44 of rewriting.)",
                "I think it's far more important to write well than most people realize.",
                "Writing doesn't just communicate ideas; it generates them.",
                "If you're bad at writing and don't like to do it, you'll miss out on most of the ideas writing would have generated.",
                "As for how to write well, here's the short version:",
                "Write a bad version 1 as fast as you can;",
                "rewrite it over and over;",
                "cut out everything unnecessary;",
                "write in a conversational tone;",
                "develop a nose for bad writing, so you can see and fix it in yours;",
                "imitate writers you like;",
                "If you can't get started, tell someone what you plan to write about, then write down what you said;",
                "expect 80% of the ideas in an essay to happen after you start writing it,",
                "and 50% of those you start with to be wrong;",
                "be confident enough to cut;",
                "have friends you trust read your stuff and tell you which bits are confusing or drag;",
                "don't (always) make detailed outlines;",
                "mull ideas over for a few days before writing;",
                "carry a small notebook or scrap paper with you;",
                "start writing when you think of the first sentence;",
                "if a deadline forces you to start before that, just say the most important sentence first;",
                "write about stuff you like;",
                "don't try to sound impressive;",
                "don't hesitate to change the topic on the fly;",
                "use footnotes to contain digressions;",
                "use anaphora to knit sentences together;",
                "read your essays out loud to see (a) where you stumble over awkward phrases and (b) which bits are boring (the paragraphs you dread reading);",
                "try to tell the reader something new and useful;",
                "work in fairly big quanta of time;",
                "when you restart, begin by rereading what you have so far;",
                "when you finish, leave yourself something easy to start with;",
                "accumulate notes for topics you plan to cover at the bottom of the file;",
                "don't feel obliged to cover any of them;",
                "write for a reader who won't read the essay as carefully as you do,",
                "just as pop songs are designed to sound ok on crappy car radios;",
                "if you say anything mistaken, fix it immediately;",
                "ask friends which sentence you'll regret most;",
                "go back and tone down harsh remarks;",
                "publish stuff online, because an audience makes you write more, and thus generate more ideas;",
                "print out drafts instead of just looking at them on the screen;",
                "use simple, germanic words;",
                "learn to distinguish surprises from digressions;",
                "learn to recognize the approach of an ending, and when one appears, grab it."
            ]
        }
    },
    "makersschedule": {
        "en": {
            "title": "Maker's Schedule, Manager's Schedule",
            "author": "Paul Graham",
            "date": "July 2009",
            "name": "makersschedule",
            "lang": "en",
            "url": "http://www.paulgraham.com/makersschedule.html",
            "fr": [
                "One reason programmers dislike meetings so much is that they're on a different type of schedule from other people.",
                "Meetings cost them more.",
                "There are two types of schedule, which I'll call the manager's schedule and the maker's schedule.",
                "The manager's schedule is for bosses.",
                "It's embodied in the traditional appointment book, with each day cut into one hour intervals.",
                "You can block off several hours for a single task if you need to, but by default you change what you're doing every hour.",
                "When you use time that way, it's merely a practical problem to meet with someone.",
                "Find an open slot in your schedule, book them, and you're done.",
                "Most powerful people are on the manager's schedule.",
                "It's the schedule of command.",
                "But there's another way of using time that's common among people who make things, like programmers and writers.",
                "They generally prefer to use time in units of half a day at least.",
                "You can't write or program well in units of an hour.",
                "That's barely enough time to get started.",
                "When you're operating on the maker's schedule, meetings are a disaster.",
                "A single meeting can blow a whole afternoon, by breaking it into two pieces each too small to do anything hard in.",
                "Plus you have to remember to go to the meeting.",
                "That's no problem for someone on the manager's schedule.",
                "There's always something coming on the next hour; the only question is what.",
                "But when someone on the maker's schedule has a meeting, they have to think about it.",
                "For someone on the maker's schedule, having a meeting is like throwing an exception.",
                "It doesn't merely cause you to switch from one task to another; it changes the mode in which you work.",
                "I find one meeting can sometimes affect a whole day.",
                "A meeting commonly blows at least half a day, by breaking up a morning or afternoon.",
                "But in addition there's sometimes a cascading effect.",
                "If I know the afternoon is going to be broken up, I'm slightly less likely to start something ambitious in the morning.",
                "I know this may sound oversensitive, but if you're a maker, think of your own case.",
                "Don't your spirits rise at the thought of having an entire day free to work, with no appointments at all?",
                "Well, that means your spirits are correspondingly depressed when you don't.",
                "And ambitious projects are by definition close to the limits of your capacity.",
                "A small decrease in morale is enough to kill them off.",
                "Each type of schedule works fine by itself.",
                "Problems arise when they meet.",
                "Since most powerful people operate on the manager's schedule, they're in a position to make everyone resonate at their frequency if they want to.",
                "But the smarter ones restrain themselves, if they know that some of the people working for them need long chunks of time to work in.",
                "Our case is an unusual one.",
                "Nearly all investors, including all VCs I know, operate on the manager's schedule.",
                "But Y Combinator runs on the maker's schedule.",
                "Rtm and Trevor and I do because we always have, and Jessica does too, mostly, because she's gotten into sync with us.",
                "I wouldn't be surprised if there start to be more companies like us.",
                "I suspect founders may increasingly be able to resist, or at least postpone, turning into managers, just as a few decades ago they started to be able to resist switching from jeans to suits.",
                "How do we manage to advise so many startups on the maker's schedule?",
                "By using the classic device for simulating the manager's schedule within the maker's: office hours.",
                "Several times a week I set aside a chunk of time to meet founders we've funded.",
                "These chunks of time are at the end of my working day, and I wrote a signup program that ensures all the appointments within a given set of office hours are clustered at the end.",
                "Because they come at the end of my day these meetings are never an interruption.",
                "(Unless their working day ends at the same time as mine, the meeting presumably interrupts theirs, but since they made the appointment it must be worth it to them.)",
                "During busy periods, office hours sometimes get long enough that they compress the day, but they never interrupt it.",
                "When we were working on our own startup, back in the 90s,",
                "I evolved another trick for partitioning the day.",
                "I used to program from dinner till about 3 am every day, because at night no one could interrupt me.",
                "Then I'd sleep till about 11 am, and come in and work until dinner on what I called \"business stuff.\"",
                "I never thought of it in these terms, but in effect I had two workdays each day, one on the manager's schedule and one on the maker's.",
                "When you're operating on the manager's schedule you can do something you'd never want to do on the maker's: you can have speculative meetings.",
                "You can meet someone just to get to know one another.",
                "If you have an empty slot in your schedule, why not?",
                "Maybe it will turn out you can help one another in some way.",
                "Business people in Silicon Valley (and the whole world, for that matter) have speculative meetings all the time.",
                "They're effectively free if you're on the manager's schedule.",
                "They're so common that there's distinctive language for proposing them: saying that you want to \"grab coffee,\" for example.",
                "Speculative meetings are terribly costly if you're on the maker's schedule, though.",
                "Which puts us in something of a bind.",
                "Everyone assumes that, like other investors, we run on the manager's schedule.",
                "So they introduce us to someone they think we ought to meet, or send us an email proposing we grab coffee.",
                "At this point we have two options, neither of them good: we can meet with them, and lose half a day's work; or we can try to avoid meeting them, and probably offend them.",
                "Till recently we weren't clear in our own minds about the source of the problem.",
                "We just took it for granted that we had to either blow our schedules or offend people.",
                "But now that I've realized what's going on, perhaps there's a third option: to write something explaining the two types of schedule.",
                "Maybe eventually, if the conflict between the manager's schedule and the maker's schedule starts to be more widely understood, it will become less of a problem.",
                "Those of us on the maker's schedule are willing to compromise.",
                "We know we have to have some number of meetings.",
                "All we ask from those on the manager's schedule is that they understand the cost."
            ],
            "de": [
                "One reason programmers dislike meetings so much is that they're on a different type of schedule from other people.",
                "Meetings cost them more.",
                "There are two types of schedule, which I'll call the manager's schedule and the maker's schedule.",
                "The manager's schedule is for bosses.",
                "It's embodied in the traditional appointment book, with each day cut into one hour intervals.",
                "You can block off several hours for a single task if you need to, but by default you change what you're doing every hour.",
                "When you use time that way, it's merely a practical problem to meet with someone. Find an open slot in your schedule, book them, and you're done.",
                "Most powerful people are on the manager's schedule. It's the schedule of command.",
                "But there's another way of using time that's common among people who make things, like programmers and writers. They generally prefer to use time in units of half a day at least. You can't write or program well in units of an hour. That's barely enough time to get started.",
                "When you're operating on the maker's schedule, meetings are a disaster. A single meeting can blow a whole afternoon, by breaking it up into two pieces each too small to do anything hard in. Plus you have to remember to go to the meeting. That's no problem for someone on the manager's schedule. There's always something coming on the next hour; the only question is what.",
                "But when someone on the maker's schedule has a meeting, they have to think about it. For someone on the maker's schedule, having a meeting is like throwing an exception. It doesn't merely cause you to switch from one task to another; it changes the mode in which you work. I find one meeting can sometimes affect a whole day.",
                "A meeting commonly blows at least half a day, by breaking up a morning or afternoon. But in addition there's sometimes a cascading effect. If I know the afternoon is going to be broken up, I'm slightly less likely to start something ambitious in the morning.",
                "I know this may sound oversensitive, but if you're a maker, think of your own case. Don't your spirits rise at the thought of having an entire day free to work, with no appointments at all? Well, that means your spirits are correspondingly depressed when you don't. And ambitious projects are by definition close to the limits of your capacity. A small decrease in morale is enough to kill them off.",
                "Each type of schedule works fine by itself. Problems arise when they meet. Since most powerful people operate on the manager's schedule, they're in a position to make everyone resonate at their frequency if they want to.",
                "But the smarter ones restrain themselves, if they know that some of the people working for them need long chunks of time to work in.",
                "Our case is an unusual one. Nearly all investors, including all VCs I know, operate on the manager's schedule. But Y Combinator runs on the maker's schedule. Rtm and Trevor and I do because we always have, and Jessica does too, mostly, because she's gotten into sync with us. I wouldn't be surprised if there start to be more companies like us.",
                "I suspect founders may increasingly be able to resist, or at least postpone, turning into managers, just as a few decades ago they started to be able to resist switching from jeans to suits.",
                "How do we manage to advise so many startups on the maker's schedule? By using the classic device for simulating the manager's schedule within the maker's: office hours. Several times a week I set aside a chunk of time to meet founders we've funded. These chunks of time are at the end of my working day, and I wrote a signup program that ensures all the appointments within a given set of office hours are clustered at the end. Because they come at the end of my day these meetings are never an interruption. (Unless their working day ends at the same time as mine, the meeting presumably interrupts theirs, but since they made the appointment it must be worth it to them.) During busy periods, office hours sometimes get long enough that they compress the day, but they never interrupt it."
            ]
        },
        "fr": {
            "title": "Emploi du temps du cr\u00e9ateur, emploi du temps du cadre",
            "author": "Emmanuel \u00c0",
            "date": "Juillet 2009",
            "name": "makersschedule",
            "lang": "fr",
            "url": "http://versionfrancaise.blogspot.com/2009/07/emploi-du-temps-du-createur-emploi-du.html",
            "en": [
                "Une des raisons qui fait que les programmeurs n'aiment pas les r\u00e9unions, c'est qu'ils sont sur un autre type d'emploi du temps que les autres.",
                "Les r\u00e9unions leur co\u00fbtent plus.",
                "Il existe deux types d'emplois du temps, que je vais appeler l'emploi du temps du cadre et l'emploi du temps du cr\u00e9ateur.",
                "L'emploi du temps du cadre est pour les patrons.",
                "Il s'incarne dans le traditionnel agenda de rendez-vous, chaque jour \u00e9tant d\u00e9coup\u00e9 en intervalles d'une heure.",
                "On peut bloquer plusieurs heures pour une seule t\u00e2che si on en a besoin, mais par d\u00e9faut, on change d'activit\u00e9 toutes les heures.",
                "Lorsqu'on utilise le temps de cette fa\u00e7on, rencontrer quelqu'un n'est qu'une question pratique.",
                "On trouve un cr\u00e9neau horaire dans son emploi du temps, on r\u00e9serve un rendez-vous, et c'est termin\u00e9.",
                "La plupart des gens puissants sont sur l'emploi du temps du cadre.",
                "C'est l'emploi du temps du pouvoir.",
                "Mais il est une autre fa\u00e7on d'utiliser le temps, r\u00e9pandue chez les personnes qui fabriquent des choses, telles que les programmeurs et les \u00e9crivains.",
                "Ceux-ci pr\u00e9f\u00e8rent g\u00e9n\u00e9ralement utiliser leur temps en unit\u00e9s d'une demi-journ\u00e9e au moins.",
                "On ne peut pas \u00e9crire ou programmer en unit\u00e9s d'une heure.",
                "C'est \u00e0 peine assez pour se mettre en route.",
                "Lorsqu'on fonctionne sur l'emploi du temps du cr\u00e9ateur, les r\u00e9unions sont une catastrophe.",
                "Une seule r\u00e9union peut d\u00e9truire toute une apr\u00e8s-midi, la d\u00e9coupant en deux plages trop petites pour y faire avancer quelque chose de difficile.",
                "Et en plus, on doit penser \u00e0 aller \u00e0 la r\u00e9union.",
                "Ce n'est pas un probl\u00e8me pour quelqu'un qui fonctionne sur l'emploi du temps du cadre.",
                "Il y a toujours quelque chose \u00e0 venir dans l'heure suivante, la seule question est de savoir quoi.",
                "Mais quand quelqu'un qui fonctionne sur l'emploi du temps du cr\u00e9ateur a une r\u00e9union, il doit y penser.",
                "Pour quelqu'un sur l'emploi du temps du cr\u00e9ateur, avoir une r\u00e9union, c'est comme signaler une exception.",
                "Ce n'est pas seulement qu'on passe \u00e0 une autre t\u00e2che; on change le mode dans lequel on travaille.",
                "Je me suis rendu compte qu'une r\u00e9union peut parfois affecter une journ\u00e9e enti\u00e8re.",
                "Il est courant qu'au moins une demi-journ\u00e9e soit d\u00e9truite par une r\u00e9union qui coupe une matin\u00e9e ou une apr\u00e8s-midi.",
                "Mais \u00e0 cela, s'ajoute parfois un effet de dominos.",
                "Si je sais que l'apr\u00e8s-midi va \u00eatre coup\u00e9e, je suis un peu moins susceptible de commencer quelque chose d'ambitieux dans la matin\u00e9e.",
                "Je sais que je peux sembler hypersensible, mais si vous \u00eates un cr\u00e9ateur, pensez \u00e0 votre propre cas.",
                "N'a-t-on pas l'esprit plus alerte, \u00e0 la pens\u00e9e d'une journ\u00e9e enti\u00e8rement libre pour travailler, sans aucun rendez-vous?",
                "Eh bien, cela signifie qu'on a l'esprit d'autant d\u00e9prim\u00e9 quand ce n'est pas le cas.",
                "Et les projets ambitieux sont, par d\u00e9finition, proches des limites de nos capacit\u00e9s.",
                "Une petite baisse de moral est suffisante pour les abattre.",
                "Chaque type d'emploi du temps fonctionne tr\u00e8s bien en lui-m\u00eame.",
                "Les probl\u00e8mes surgissent quand les deux se rencontrent.",
                "Puisque la plupart des gens puissants fonctionnent sur l'emploi du temps du cadre, ils sont en mesure de mettre tout le monde \u00e0 leur rythme s'ils le souhaitent.",
                "Mais les plus intelligents se ma\u00eetrisent, s'ils savent que certaines personnes travaillant pour eux ont besoin de temps en longues plages.",
                "Notre cas [\u00e0 Y Combinator, l'entreprise de capital-risque dans laquelle l'auteur est un associ\u00e9] est inhabituel.",
                "Presque tous les investisseurs, y compris tous les capital-risqueurs que je connais, fonctionnent sur l'emploi du temps du cadre.",
                "Mais Y Combinator fonctionne sur l'emploi du temps du cr\u00e9ateur.",
                "Rtm, Trevor et moi le faisons parce que nous l'avons toujours fait, et Jessica le fait essentiellement parce qu'elle s'est mise en phase avec nous.",
                "Je ne serais pas surpris qu'il commence \u00e0 y avoir plus d'entreprises comme la n\u00f4tre.",
                "Il me semble que les fondateurs seront de plus en plus capables de r\u00e9sister \u00e0 leur mutation en cadres, ou au moins de retarder celle-ci (tout comme, il y a quelques d\u00e9cennies, ils ont commenc\u00e9 \u00e0 garder leurs habits de travail au lieu de se mettre \u00e0 la cravate).",
                "Comment r\u00e9ussissons-nous \u00e0 conseiller de nombreuses start-ups fonctionnant sur l'emploi du temps du cr\u00e9ateur?",
                "En utilisant le dispositif classique pour simuler l'emploi du temps du cadre au sein de celui du cr\u00e9ateur: les heures de bureau.",
                "Plusieurs fois par semaine, je mets de c\u00f4t\u00e9 une plage de temps pour rencontrer les fondateurs que nous avons financ\u00e9.",
                "Ces plages de temps sont \u00e0 la fin de ma journ\u00e9e de travail, et j'ai \u00e9crit un programme d'inscription afin que tous les rendez-vous soient regroup\u00e9s \u00e0 la fin d'un ensemble d'heures de bureau.",
                "Parce qu'elles arrivent en fin de journ\u00e9e, ces r\u00e9unions ne sont jamais une interruption.",
                "(Sauf si leur journ\u00e9e de travail se termine en m\u00eame temps que la mienne, la r\u00e9union interrompt probablement la leur, mais s'ils ont pris rendez-vous, c'est que cela doit \u00eatre rentable pour eux.)",
                "Durant les p\u00e9riodes charg\u00e9es, les heures de bureau deviennent parfois si longues qu'elles r\u00e9duisent la journ\u00e9e, mais elles ne interrompent jamais.",
                "Lorsque nous travaillions dans notre propre start-up dans les ann\u00e9es 90,",
                "J'avais d\u00e9velopp\u00e9 un autre truc pour partitionner la journ\u00e9e.",
                "Je programmais du d\u00eener jusque vers 3 heures du matin chaque jour, parce que la nuit, personne ne pouvait m'interrompre.",
                "Ensuite, je dormais jusque vers 11 heures, et je venais travailler jusqu'au d\u00eener \u00e0 ce que j'appelais \"le business\".",
                "Je n'y avais jamais pens\u00e9 en ces termes, mais de fait, j'avais deux journ\u00e9es de travail chaque jour, l'une sur l'emploi du temps du cadre, et une sur celui du cr\u00e9ateur.",
                "Lorsqu'on fonctionne sur l'emploi du temps du cadre, on peut faire une chose qu'il n'est pas question de faire sur celui du cr\u00e9ateur: on peut faire des r\u00e9unions sp\u00e9culatives.",
                "On peut rencontrer quelqu'un, simplement pour faire connaissance.",
                "Si on a un emplacement vide dans son emploi du temps, pourquoi pas?",
                "Peut-\u00eatre qu'on se rendra compte qu'on peut s'aider en quelque chose.",
                "Les hommes d'affaire de la Silicon Valley (et du monde entier, d'ailleurs) ont des r\u00e9unions sp\u00e9culatives tout le temps.",
                "Elles sont effectivement gratuites si on est sur l'emploi du temps du cadre.",
                "Elles sont si fr\u00e9quentes qu'il y a un langage expr\u00e8s pour les proposer: dire qu'on va \"prendre un petit caf\u00e9\", par exemple.",
                "Les r\u00e9unions sp\u00e9culatives sont terriblement co\u00fbteuses si on est sur l'emploi du temps du cr\u00e9ateur, cependant.",
                "Ce qui nous met un peu en situation de d\u00e9pendance.",
                "Tout le monde suppose que, comme les autres investisseurs, nous marchons sur un emploi du temps du cadre.",
                "Donc, on nous pr\u00e9sente \u00e0 des gens qu'on pense que nous devrions rencontrer, ou on nous envoie des mails nous proposant de prendre un petit caf\u00e9.",
                "\u00c0 ce moment, nous avons deux possibilit\u00e9s, mauvaises toutes les deux: nous pouvons rencontrer les gens, et perdre une demi-journ\u00e9e de travail; ou nous pouvons essayer d'\u00e9viter de les rencontrer, et probablement les offenser.",
                "Jusque r\u00e9cemment, nous-m\u00eames n'avions pas d'id\u00e9e claire sur la source du probl\u00e8me.",
                "Nous nous \u00e9tions r\u00e9sign\u00e9s \u00e0 avoir le choix entre d\u00e9truire notre emploi du temps et offenser les gens.",
                "Mais maintenant que j'ai compris ce qui se passe, peut-\u00eatre y a-t-il une troisi\u00e8me possibilit\u00e9: \u00e9crire quelque chose qui explique les deux types d'emploi du temps.",
                "Peut-\u00eatre qu'\u00e0 terme, si le conflit entre l'emploi du temps du cadre et l'emploi du temps du cr\u00e9ateur commence \u00e0 \u00eatre mieux compris, cela deviendra moins probl\u00e9matique.",
                "Nous qui sommes sur l'emploi du temps du cr\u00e9ateur, sommes pr\u00eats \u00e0 faire des compromis.",
                "Nous savons que nous devons avoir un certain nombre de r\u00e9unions.",
                "Tout ce que nous demandons \u00e0 ceux qui sont sur l'emploi du temps du cadre, c'est de comprendre ce que cela nous co\u00fbte."
            ]
        },
        "de": {
            "title": "Zeitpl\u00e4ne von Machern und Managern",
            "author": "Robert Schultze-Jena",
            "date": "Juli 2009",
            "name": "makersschedule",
            "lang": "de",
            "url": "https://blog.robertsj.com/makers-schedule-managers-schedule/",
            "en": [
                "Dass Programmierer Meetings nicht m\u00f6gen liegt u.a. daran, dass sie sich an einem anderen Zeitplan orientieren als die meisten Menschen.",
                "Meetings sind f\u00fcr sie kostspieliger.",
                "Es gibt zwei Arten von Zeitpl\u00e4nen, welche ich den Zeitplan von Machern und den Zeitplan von Managern nenne (\"maker's schedule, manager's schedule\").",
                "Der Zeitplan von Managern f\u00fcgt sich gut in den traditionellen Kalender ein, welcher jeden Tag in einst\u00fcndige Intervalle unterteilt.",
                "Man kann mehrere Stunden auf einmal blockieren, wenn dies eine Aufgabe erfordert, aber die Standard Vorgabe ist auf st\u00fcndliche Abwechslung angelegt.",
                "Wenn Zeit auf diese Weise genutzt wird, ist es lediglich ein praktisches Problem sich mit jemandem zu treffen. Man muss nur einen offenen Zeitabschnitt im Kalender finden und das Treffen eintragen.",
                "Die meisten einflussreichen Menschen operieren auf dem Zeitplan von Managern. Es ist der herk\u00f6mmliche Modus Operandi.",
                "Es gibt aber eine andere Form der Zeitnutzung, welche h\u00e4ufig von Menschen angewandt wird, welche Dinge herstellen, wie Programmierer und Schriftsteller. Sie nutzen ihre Zeit normalerweise am liebsten in Einheiten von mindestens einem halben Tag.",
                "In Abschnitten von einer Stunde kann man kein Programm schreiben. Das ist gerade mal genug Zeit um damit anzufangen.",
                "Wenn man sich auf dem Zeitplan von Machern befindet, sind Meetings eine Katastrophe. Ein einzelnes Meeting kann einen ganzen Nachmittag in Mitleidenschaft ziehen, indem er in Zeitabschnitte aufgebrochen wird, die einzeln genommen zu klein sind, um darin etwas anspruchsvolles in Angriff zu nehmen. Hinzu kommt, dass man erinnern muss, zu dem Meeting zu gehen.",
                "F\u00fcr jemdanem auf dem Zeitplan des Machers ist ein Meeting wie eine Ausnahme. Es bedeutet nicht nur von einer Aufgabe zur n\u00e4chsten \u00fcberzugehen. Es \u00e4ndert auch die Art- und Weise zu arbeiten. Ich finde, dass ein einzelnens Meeting den ganzen Tag beeinflussen kann.",
                "Ein Meeting zerst\u00f6rt normalerweise mindestens einen halben Tag, indem es einen Morgen oder Nachmittag unterbricht. Hinzu kommt ein kumulativer Effekt. Wenn ich weiss, dass der Nachmittag unterbrochen wird, bin ich etwas weniger geneigt etwas neues und anspruchsvolles am Morgen in Angriff zu nehmen.",
                "Ich bin mir bewusst, dass dies \u00fcbertrieben sensibel klingen mag, aber wenn sie ein Macher sind, denken sie an ihre eigene Situation. Steigt ihr Animus nicht bei dem Gedanken daran, einen gesamten Tag f\u00fcr Ihre Arbeit frei zu haben, ohne jegliche Termine? Dies bedeutet im Umkehrschluss, dass sie entsprechend deprimiert sind, wenn dies nicht der Fall ist. Und anspruchsvolle Projekte sind ihrer Grundart nach nah an der Grenze ihrer eigenen M\u00f6glichkeiten. Bereits ein geringer Mangel an Moral ist genug, um sie zum scheitern zu bringen.",
                "Jeder dieser beiden Formen der Zeitplanung funktioniert getrennt voneinander. Probleme treten auf, wenn sie aufeinander treffen. Da die meisten einflussreichen Menschen auf dem Zeitplan von Managern operieren, befinden sie sich in der Position andere dazu zu bringen auf sie einzugehen, wenn sie dies w\u00fcnschen.",
                "Die schlaueren von ihnen halten sich damit zur\u00fcck, da sie wissen, dass einige derjenigen, die f\u00fcr sie arbeiten lange Zeitabschnitte ben\u00f6tigen.",
                "Unser Fall ist ungew\u00f6hnlich. Nahezu alle Investoren und alle Risikokapitalgeber, die ich kenne, operieren auf dem Zeitplan von Managern. Y Combinator jedoch orientiert sich am Zeitplan von Machern. F\u00fcr Rtm, Trevor und mich war dies von jeher der Fall und f\u00fcr Jessica ebenfalls, haupts\u00e4chlich, da sie sich an uns angepasst hat. Ich w\u00fcrde mich nicht wundern, wenn mehrere Firmen zunehmend das gleiche tun.",
                "Ich vermute, dass Gr\u00fcnder zunehmend in der Lage sein werden, dem \u00dcbergang zu Managern zu widerstehen oder zumindest aufzuschieben, genauso wie sie vor einigen Jahrzehnten anfingen, dem Tragen von Anz\u00fcgen anstelle von Jeans zu widerstehen.",
                "Wie gelingt es uns so viele Startups, welche sich auf dem Zeitplan von Machern befinden zu beraten? Indem wir den klassischen Ansatz verfolgen, den Zeitplan von Managern innerhalb des Zeitplans von Machern zu simulieren: mittels Sprechstunden. Mehrere Male pro Woche nehme ich mir einen Zeitabschnitt frei, um mich mit Gr\u00fcndern zu treffen, in die wir investiert haben. Diese Zeit ist am Ende meines Arbeitstages und ich habe ein Anmeldeprogramm geschrieben, welches sicher stellt, dass sich alle Termine innerhalb der Sprechstunden am Ende h\u00e4ufen. Da sie am Ende des Tages statt finden, sind sie niemals eine Unterbrechung. (Nur wenn der Arbeitstag der Gr\u00fcnder zur gleichen Zeit wie meiner endet, ist es keine Unterbrechung f\u00fcr sie. Aber da sie den Termin gemacht haben, muss ihnen dies wert sein.) In sehr besch\u00e4ftigten Zeiten sind die Sprechstunden so lang, dass sie die restliche Zeit des Tages einschr\u00e4nken, jedoch niemals unterbrechen."
            ]
        }
    }
}